name: build and deploy app
on: [push, pull-request]
jobs:
  job1:
    runs_on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: say hi
        run: echo "hi"        