version: "3"
services:
  api:
    image: jungmatheus/book-api
    depends_on:
      - postgres
    ports: 
      - 80:8000
    volumes:
      - ./:/usr/src/app:ro
    environment:
     - DATABASE_USERNAME=${DATABASE_USERNAME}
     - DATABASE_NAME=${DATABASE_NAME}
     - DATABASE_PASSWORD=${DATABASE_PASSWORD}
     - SECRET_KEY=${SECRET_KEY}
     - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
     - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
     - ALGORITHM=${ALGORITHM}
     - DATABASE_PORT=${DATABASE_PORT}
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes: 
  postgres-db: