version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports: 
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    environment:
     - DATABASE_USERNAME=postgres
     - DATABASE_NAME=bookish
     - DATABASE_PASSWORD=lösenord123
     - SECRET_KEY=ddd80a711e1f3cb938d2bf638e9e402ac842e8dc0a674c48ad59e12dd47df0e4
     - DATABASE_HOSTNAME=postgres
     - ACCESS_TOKEN_EXPIRE_MINUTES=60
     - ALGORITHM=HS256
     - DATABASE_PORT=5432
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=lösenord123
      - POSTGRES_DB=bookish
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes: 
  postgres-db: